disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "ezruh.xyz"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[[params.author.links]]
github = "https://github.com/ez-ruh"

["params.author"]
name = "Ezra Treasure"
